export 'package:genesis/presentation/NavBar/nav_bar.screen.dart';
export 'package:genesis/presentation/RolesCapacities/roles_capacities.screen.dart';
export 'package:genesis/presentation/Splash/splash.screen.dart';
export 'package:genesis/presentation/dashboard/dashboard.screen.dart';
export 'package:genesis/presentation/getStarted/get_started.screen.dart';
export 'package:genesis/presentation/home/home.screen.dart';
export 'package:genesis/presentation/login/login.screen.dart';
export 'package:genesis/presentation/profile/profile.screen.dart';
export 'package:genesis/presentation/userList/user_list.screen.dart';